### PR TITLE
Added regex to extract the path so that we can compare the correct pa…

### LINKED ISSUE #178: Browser Tab Not Selected
With recent updates the file browser tab is not selected even when viewing the file browser:

browser

### PR DESCRIPTION
**Pull request by gabedealmeida**
…ths to one another.

### CODE REVIEW

**Comment by montyanderson** [comment]
What does this do precisely?

**Comment by super3** [comment]
@gabedealmeida Can you use `.startsWith` instead of regex?

**Comment by gabedealmeida** [comment]
@montyanderson This extracts the path out of the search bar and sees if it matches one of the tabs on the page to apply the `active` class. Before this implementation, there were times that we'd get a path with an ending forward slash, and other times it didn't end in a forward slash. Moreover, prior to this implementation, if we were in a nested directory, we would compare the whole path to `/apps/browser/`. So this implementation covers all of those bases.

**Comment by gabedealmeida** [comment]
@super3 Not in this particular case because we reuse this functionality to know when to select the `browser,` `apps,` and the `usage` tab.

**Comment by gabedealmeida** [comment]
@super3 I refactored to use `includes` instead

**Comment by montyanderson** [comment]
@gabedealmeida I think you need to use `String.prototype.startsWith` as `includes()` could mean `/app/browser/apps/`

**Pull request merged**
