### PR TITLE
Preliminary tests written for all routes with a focus on the main use…

### LINKED ISSUE #158: Write Server Tests
Test that requests made to our exposed backend return the appropriate data. This test is not supposed to intercept requests and/or mock database connections. The goal is to test requests made to the endpoints we expose regardless of which DB the server is connected to.

### PR DESCRIPTION
**Pull request by gabedealmeida**
…r interacted routes.

### CODE REVIEW

**Comment by gabedealmeida** [comment]
@super3 This should be good to go for testing and merging! :)

**Comment by montyanderson** [comment]
@gabedealmeida Isn't `UUID()` different every time it's called?

**Comment by gabedealmeida** [comment]
@montyanderson Yes. I chose the UUID route so that every assertion is testing an entirely new account on a unit basis, and not relying on the results of previous tests. Given that after every test run we are to wipe the containers, if we create a few random accounts it doesn't matter. If you look into every assertion you will see that the ones that require an account to be logged in or created, there are setup steps to do so.

**Comment by montyanderson** [comment]
@gabedealmeida Do you think we could remove the UUID dependency?

```
const crypto = require("crypto");

const generateId = () => crypto.randomBytes(16).toString("hex");
```

and use `generateId()` instead of `UUID()`?

**Comment by gabedealmeida** [comment]
@montyanderson I have no problem with that. Out of curiosity, why do you prefer the crypto package for something like this?

**Comment by montyanderson** [comment]
@gabedealmeida It's built in and likely what UUID uses under the surface.

**Comment by gabedealmeida** [comment]
Sounds good. I'll replace it with crypto.

**Pull request merged**
